### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by MarvelGa** [MarvelGa/homepage#8]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by evgen8888** [comment]
EXPERIENCE

1968
Began my career at my father's real estate development company, Elizabeth Trump & Son

1971
Was promoted to president of the company and renamed it The Trump Organization

1978
Purchased a 50 percent stake in the derelict Commodore Hotel and turned it into the Grand Hyatt Hotel in 2 years of remodeling

1980
Started developing the Trump Tower skyscraper in Manhattan, I payed a crew of undocumented Polish workers to demolish the historic Bonwit Teller store, including art deco features. All this to make architectural critic Paul Goldberger say in 1983 that the tower's atrium is "the most pleasant interior public space to be completed in New York in some years". At the same time I also started a repair job on the Wollman Rink in Central Park and completed the work in three months for $1.95 million, which was $775,000 less than the initial budget! 

1983 
I purchased New Jersey Generals, an American football team. I changed team's play schedule and filed an antitrust lawsuit against United States Football League, so NJG are not doing so good now, but back then they were great! 

1985 
I bought the Mar-a-Lago estate in Palm Beach and turned it into a private club.You can join if you pay $200K initiation fee (and there is another annual fee for members, it is very expensive to be rich). That year I also opened a casino called Trump Castle. My wife Ivana became a manager, because she is another Trump! 

1987
Registered as a Republican

1988 
Acquired the Plaza Hotel in Manhattan for $407 million, invested $50 million to restore the building and boosted it from three-star to four-star hotel (I called it "the Mona Lisa" and sold it for a lot of cash in 1995) 

1989, 1990
Learned about Tour de France and decided to hold my very own Tour de Trump. Is America not great enough for that cycling competition? 

1989 — 1992 
Ran a second hand airline called Trump Shuttle. What a waste of money, I had to sell it, now it is American Airlines Shuttle, btw 

1994
Refurbished the the Gulf and Western Building on Columbus Circle, turned it into a 44-story luxury property known as Trump International Hotel and Tower 

1996
Acquired the Bank of Manhattan Trust Building, which was a vacant seventy-one story skyscraper on Wall Street. After an extensive renovation, the high-rise was renamed the Trump Building 

1997
Began a multi-building development along the Hudson River, which was named Trump Place. Me and the other investors sold our shares for $1.8 billion and that was then the biggest residential sale in the history of New York City 

1999 Started buying golf courses. They are very cheap, I have 18 of them now in USA and abroad! Also switched to the Reform Party that year 

2001
Completed Trump World Tower and joined the Democratic Party

2002
Acquired the former Hotel Delmonico, which was renovated and reopened in 2004 as the Trump Park Avenue. I sure do like my surname! 

2005
Started Trump University with Michael Sexton and Jonathan Spitalny: no grades, certificates and other bureaucracy, but program offered courses in real estate, asset management entrepreneurship, and wealth creation. 98% students gave positive reviews while studying, however some of these ungrateful gringos filed lawsuits against Trump University after the course. I had to pay 525 million to settle that... 

2009
Changed my mind and became Republican again 

2015
Became the most important Republican nominating for presidential election run 

2016
Won election race with 77 votes more than Clinton, yippe-kee-yay! 

2017
Became 45th president of the United States 

PERSONAL LIFE
 
1977
Married Czech model Ivana Zelniekova
 
1977
My first son is born. I called him Donald, of course! 

1982
Birth of Ivanka Trump
 
1984
Birth of Eric Trump
 
1992 
Started affair with Marla Maples, so I had to divorce. God knows I love nice women, Iove them all! 

1993 
Married Marla and had a daughter, we named her Tiffany, because I like Tiffany & Company jewellery as well 

1999
Divorced Marla 

1998
Met my future third wife, Melania Knauss

2005
Married her 

2006
Melania gained United States citizenship and gave birth to our son, Barron 

MEDIA CAREER 

1987
Published a book "Trump: The Art of the Deal" in coauthorship with Tony Shwartz 

1990
Published a book "Trump: Surviving at the Top" in coauthorship with Charles Leerhsen
 
1991
Was awarded Worst Supporting Actor at Golden Raspberry Awards for a part in "Ghosts Can't Do It" 

1997 
Published a book "Trump: The Art of the Comeback" in coauthorship with Kate Bohner 

2000
Published a book "Trump: The America We Deserve" in coauthorship with Dave Shiflett
 
2003 — 2015
Produced NBC reality shows "The Apprentice" and "The Celebrity Apprentice"
 
2004
Published a book "Trump: How to Get Rich" in coauthorship with Meredith McIver 

2004
Published a book "The Way to the Top: The Best Business Advice I Ever Received" 

2004
Published a book "Think Like a Billionaire: Everything You Need to Know About Success, Real Estate, and Life" in coauthorship with Meredith McIver 

2004 — 2008
Ran short-form talk radio program "Trumped!" (one to two minutes on weekdays)
 
2005
Published a book "The Best Golf Advice I Ever Received" 

2005 
Performed a song with Megan Mullally at the 57th Primetime Emmy Awards 

2006 
Published a book "Why We Want You to Be Rich" in coauthorship with Meredith McIver and Robert Kiyosaki 

2008
Published a book "Never Give Up: How I Turned My Biggest Challenges into Success" in coauthorship with Meredith McIver
 
2009
Published a book "Think Like a Champion: An Informal Education in Business and Life" in coauthorship with Meredith McIver
 
2011
Published a book "Time to Get Tough: Making America #1 Again" in coauthorship with Wynton Hall, Peter Schweizer and Meredith McIver
 
2011
Published a book "Midas Touch: Why Some Entrepreneurs Get Rich - And Why Most Don't" in coauthorship with Robert Kiyosaki 

2011
Published a book "Trump Tower" in coauthorship with Jeffrey Robinson 

2015
Published a book "Crippled America: How to Make America Great Again" 

2019 Was awarded Worst Actor and Worst Screen Combo at Golden Raspberry Awards for parts in "Death of a Nation" and "Fahrenheit 11/9" 

EDUCATION 

1959
Enrolled in the New York Military Academy, a private boarding school, after my parents discovered I made frequent trips into Manhattan without their permission
 
1964
Started studying in Fordham University
 
1966
Transferred to the Wharton School of the University of Pennsylvania and graduated in May 1968 with a B.S. in economics 

2011 
Asked Mends who are prominent and wealthy alumni of the New York Military Academy to secure my academic records so they could not be seen by anyone, never!

**Comment by evgen8888** [comment]
<h3>EXPIRIENCE</h3>
                  <h6>Recent</h6>
                  <ul class="timeline">
                    <li>
                      <p><em>2017</em></p>
                      <p>Became 45th president of the United States</p>
                    </li>
                  </ul>
                  <h6>Back then</h6>
                  <ul class="timeline">
                    <li>
                      <p><em>2016</em></p>
                      <p>Won election race with 77 votes more than Clinton, yippe-kee-yay!</p>
                    </li>
                    <li>
                      <p><em>2015</em></p>
                      <p>Became the most important Republican nominating for presidential election run</p>
                    </li>
                    <li>
                      <p><em>2009</em></p>
                      <p>Changed my mind and became Republican again</p>
                    </li>
                    <li>
                      <p><em>2005</em></p>
                      <p>Started Trump University with Michael Sexton and Jonathan Spitalny: no grades, certificates and other bureaucracy, but program offered courses in real estate, asset management entrepreneurship, and wealth creation. 98% students gave positive reviews while studying, however some of these ungrateful gringos filed lawsuits against Trump University after the course. I had to pay $25 million to settle that...</p>
                    </li>
                    <li>
                      <p><em>2002</em></p>
                      <p>Acquired the former Hotel Delmonico, which was renovated and reopened in 2004 as the Trump Park Avenue. I sure do like my surname!</p>
                    </li>
                    <li>
                      <p><em>2001</em></p>
                      <p>Completed Trump World Tower and joined the Democratic Party</p>
                    </li>
                    <li>
                      <p><em>1999</em></p>
                      <p>Started buying golf courses. They are very cheap, I have 18 of them now in USA and abroad! Also switched to the Reform Party that year</p>
                    </li>
                    <li>
                      <p><em>1997</em></p>
                      <p>Began a multi-building development along the Hudson River, which was named Trump Place. Me and the other investors sold our shares for $1.8 billion and that was then the biggest residential sale in the history of New York City</p>
                    </li>
                    <li>
                      <p><em>1996</em></p>
                      <p>Acquired the Bank of Manhattan Trust Building, which was a vacant seventy-one story skyscraper on Wall Street. After an extensive renovation, the high-rise was renamed the Trump Building</p>
                    </li>
                    <li>
                      <p><em>1994</em></p>
                      <p>Refurbished the Gulf and Western Building on Columbus Circle, turned it into a 44-story luxury property known as Trump International Hotel and Tower</p>
                    </li>
                    <li>
                      <p><em>1989 ― 1992</em></p>
                      <p>Ran a second hand airline called Trump Shuttle. What a waste of money, I had to sell it, now it is American Airlines Shuttle, btw</p>
                    </li>
                    <li>
                      <p><em>1989, 1990</em></p>
                      <p>Learned about Tour de France and decided to hold my very own Tour de Trump. Is America not great enough for that cycling competition?</p>
                    </li>
                    <li>
                      <p><em>1988</em></p>
                      <p>Acquired the Plaza Hotel in Manhattan for $407 million, invested $50 million to restore the building and boosted it from three-star to four-star hotel (I called it "the Mona Lisa" and sold it for a lot of cash in 1995)</p>
                    </li>
                    <li>
                      <p><em>1987</em></p>
                      <p>Registered as a Republican</p>
                    </li>
                    <li>
                      <p><em>1985</em></p>
                      <p>I bought the Mar-a-Lago estate in Palm Beach and turned it into a private club.You can join if you pay $200K initiation fee (and there is another annual fee for members, it is very expensive to be rich). That year I also opened a casino called Trump Castle. My wife Ivana became a manager, because she is another Trump!</p>
                    </li>
                    <li>
                      <p><em>1983</em></p>
                      <p>I purchased New Jersey Generals, an American football team. I changed team's play schedule and filed an antitrust lawsuit against United States Football League, so NJG are not doing so good now, but back then they were great!</p>
                    </li>
                    <li>
                      <p><em>1980</em></p>
                      <p>Started developing the Trump Tower skyscraper in Manhattan, I payed a crew of undocumented Polish workers to demolish the historic Bonwit Teller store, including art deco features. All this to make architectural critic Paul Goldberger say in 1983 that the tower's atrium is "the most pleasant interior public space to be completed in New York in some years". At the same time I also started a repair job on the Wollman Rink in Central Park and completed the work in three months for $1.95 million, which was $775,000 less than the initial budget!</p>
                    </li>
                    <li>
                      <p><em>1978</em></p>
                      <p>Purchased a 50 percent stake in the derelict Commodore Hotel and turned it into the Grand Hyatt Hotel in 2 years of remodeling</p>
                    </li>
                    <li>
                      <p><em>1971</em></p>
                      <p>Was promoted to president of the company and renamed it The Trump Organization</p>
                    </li>
                    <li>
                      <p><em>1968</em></p>
                      <p>Began my career at my father's real estate development company, Elizabeth Trump & Son</p>
                    </li>
                  </ul>

**Comment by evgen8888** [comment]
<h3>PERSONAL LIFE</h3>
                  <ul class="timeline">
                    <li>
                      <p><em>2006</em></p>
                      <p>Melania gained United States citizenship and gave birth to our son, Barron</p>
                    </li>
                    <li>
                      <p><em>2005</em></p>
                      <p>Married her</p>
                    </li>
                    <li>
                      <p><em>1999</em></p>
                      <p>Met my future third wife, Melania Knauss</p>
                    </li>
                    <li>
                      <p><em>1998</em></p>
                      <p>Divorced Marla ¯_(ツ)_/¯</p>
                    </li>
                    <li>
                      <p><em>1993</em></p>
                      <p>Married Marla and had a daughter, we named her Tiffany, because I like Tiffany & Company jewellery as well</p>
                    </li>
                    <li>
                      <p><em>1992</em></p>
                      <p>Started affair with Marla Maples, so I had to divorce. God knows I love nice women, I love them all!</p>
                    </li>
                    <li>
                      <p><em>1984</em></p>
                      <p>Birth of Eric Trump</p>
                    </li>
                    <li>
                      <p><em>1982</em></p>
                      <p>Birth of Ivanka Trump</p>
                    </li>
                    <li class="details">
                      <input type="checkbox" id="other">
                      <label for="other" class="summary"><em>1977</em></label>
                      <div>
                        <ul>
                          <li>My first son is born. I called him Donald, of course!</li>
                          <li>Married Czech model Ivana Zelníčková</li>
                        </ul>
                      </div>
                    </li>
                  </ul>

**Comment by evgen8888** [comment]
<h3>MEDIA CAREER</h3>
                  <ul class="timeline">
                    <li>
                      <p><em>2019</em></p>
                      <p>Was awarded Worst Actor and Worst Screen Combo at Golden Raspberry Awards for parts in "Death of a Nation" and "Fahrenheit 11/9"</p>
                    </li>
                    <li>
                      <p><em>2015</em></p>
                      <p>Published a book "Crippled America: How to Make America Great Again"</p>
                    </li>
                    <li class="details">
                      <input type="checkbox" id="other">
                      <label for="other" class="summary"><em>2011</em></label>
                      <div>
                        <ul>
                          <li>Published a book "Time to Get Tough: Making America #1 Again" in coauthorship with Wynton Hall, Peter Schweizer and Meredith McIver</li>
                          <li>Published a book "Midas Touch: Why Some Entrepreneurs Get Rich – And Why Most Don't" in coauthorship with Robert Kiyosaki</li>
                          <li>Published a book "Trump Tower" in coauthorship with Jeffrey Robinson</li>
                        </ul>
                      </div>
                    </li>
                    <li>
                      <p><em>2009</em></p>
                      <p>Published a book "Think Like a Champion: An Informal Education in Business and Life" in coauthorship with Meredith McIver</p>
                    </li>
                    <li>
                      <p><em>2008</em></p>
                      <p>Published a book "Never Give Up: How I Turned My Biggest Challenges into Success" in coauthorship with Meredith McIver</p>
                    </li>
                    <li class="details">
                      <input type="checkbox" id="other">
                      <label for="other" class="summary"><em>2007</em></label>
                      <div>
                        <ul>
                          <li>Published a book "Think Big and Kick Ass" in coauthorship with Bill Zanker</li>
                          <li>Received a star on the Hollywood Walk of Fame for being producer of Miss Universe pageant</li>
                        </ul>
                      </div>
                    </li>
                    <li class="details">
                      <input type="checkbox" id="other">
                      <label for="other" class="summary"><em>2006</em></label>
                      <div>
                        <ul>
                          <li>Published a book "Why We Want You to Be Rich" in coauthorship with Meredith McIver and Robert Kiyosaki</li>
                          <li>Published a book "How to Build a Fortune: Your Plan for Success From the World's Most Famous Businessman"</li>
                          <li>Published a book "The Best Real Estate Advice I Ever Received: 100 Top Experts Share Their Strategies"</li>
                          <li>Published a book "Trump 101: The Way to Success" in coauthorship with Meredith McIver</li>
                        </ul>
                      </div>
                    </li>
                    <li class="details">
                      <input type="checkbox" id="other">
                      <label for="other" class="summary"><em>2005</em></label>
                      <div>
                        <ul>
                          <li>Published a book "The Best Golf Advice I Ever Received"</li>
                          <li>Performed a song with Megan Mullally at the 57th Primetime Emmy Awards</li>
                        </ul>
                      </div>
                    </li>
                    <li>
                      <p><em>2004 ― 2008</em></p>
                      <p>Ran short-form talk radio program "Trumped!" (one to two minutes on weekdays)</p>
                    </li>
                    <li class="details">
                      <input type="checkbox" id="other">
                      <label for="other" class="summary"><em>2004</em></label>
                      <div>
                        <ul>
                          <li>Published a book "Trump: How to Get Rich" in coauthorship with Meredith McIver</li>
                          <li>Published a book "The Way to the Top: The Best Business Advice I Ever Received"</li>
                          <li>Published a book "Think Like a Billionaire: Everything You Need to Know About Success, Real Estate, and Life" in coauthorship with Meredith McIver</li>
                        </ul>
                      </div>
                    </li>
                    <li>
                      <p><em>2003 ― 2015</em></p>
                      <p>Produced NBC reality shows "The Apprentice" and "The Celebrity Apprentice"</p>
                    </li>
                    <li>
                      <p><em>2000</em></p>
                      <p>Published a book "Trump: The America We Deserve" in coauthorship with Dave Shiflett</p>
                    </li>
                    <li>
                      <p><em>1997</em></p>
                      <p>Published a book "Trump: The Art of the Comeback" in coauthorship with Kate Bohner</p>
                    </li>
                    <li>
                      <p><em>1991</em></p>
                      <p>Was awarded Worst Supporting Actor at Golden Raspberry Awards for a part in "Ghosts Can't Do It"</p>
                    </li>
                    <li>
                      <p><em>1990</em></p>
                      <p>Published a book "Trump: Surviving at the Top" in coauthorship with Charles Leerhsen</p>
                    </li>
                    <li>
                      <p><em>1987</em></p>
                      <p>Published a book "Trump: The Art of the Deal" in coauthorship with Tony Shwartz</p>
                    </li>
                  </ul>

**Comment by evgen8888** [comment]
<section>
                  <h3>Languages</h3>
                  <p class="tags small"> <span class="language" lang="ru"> &#x1f1f7;&#x1f1fa; РУССКИЙ</span> <span class="language" lang="en">&#x1f1fa;&#x1f1f8; ENGLISH</span></p>
                </section>
                <section>
                  <h3>Skills</h3>
                  <p class="tags small">NEGOTIATING COUNTING REMODELING WRITING ACING SINGING REPORTING INCORPORATING SELLING ADVERTISING HOSTING COMPETING TWITTING PARENTING GAMBLING DATING SUING ORGANIZING FUNDING DEBATING ADVISING PRESBYTERIANING</p>
                </section>
                <section>
                  <h3>Character</h3>
                  <p class="tags small">ADJUSTED CALM AMBITIOUS COMPETITIVE SOCIABLE DIRECT HOSTILE CARELESS IGNORANT INQUISITIVE BOLD CONFIDENT MISCHIEVOUS CHARMING INTERESTING DARING COLORFUL LAZY SELF-PROMOTING</p>
                </section>
                <section>
                  <h3>Likes&#x1f603;</h3>
                  <img src="https://media.giphy.com/media/wJNGA01o1Zxp6/giphy.gif" class="gif">
                  <p class="tags small"> <a href="https://www.youtube.com/watch?v=u_aLESDql1U">BILLIONS</a> FILET-O-FISH BIG MAC <a href="https://www.youtube.com/watch?v=RDrfE9I8_hs">CHINA</a> QUARTER POUNDER DIET COKE TARIFFS BIBLE ARTOF DEAL PATRIOTS BEAUTIFUL MODELS GOLD REAL ESTATE WAR PROTESTERS CONSTRUCTION RUSSIANS BANKS SPORTS WOMEN MEXICO RED HAT KOREANS GOLF EVERYBODY <a href="https://www.youtube.com/watch?v=0f9ysmciWUk"><sup>[1]</sup></a> <a href="https://www.youtube.com/watch?v=TTdmKaXAfAs"><sup>[2]</sup></a></p>
                </section>
                <section>
                  <h3>Dislikes&#x1f61e;</h3>
                  <img src="https://media.giphy.com/media/l41YfnhA7QNddFD0Y/giphy.gif" class="gif">
                  <p class="tags small">DOGS MEDIA CNN GERMANS MEXICANS IMMIGRANTS SHITHOLE COUNTRIES UNATTRACTIVE WOMEN BLACKS SUSHI HOT-DOGS ALCOHOL FRUIT CHRISTMAS PARTIES LIBERALS</p>
                </section>
                <section>
                  <h3>Wants&#x1f97a;</h3>
                  <img src="https://media.giphy.com/media/ySFtYLc51D3pK/giphy.gif" class="gif">
                  <p class="tags small bulleted"><span class="tag">BE HEALTHY </span> <span class="tag">GROW A TREE </span><span class="tag">BUILD TRUMP AIRPORT </span> <span class="tag">HAVE A TASTE </span> <span class="tag">DO A HARLEM SHAKE IN CONGRESS </span> <span class="tag">TO GOLF MORE OFTEN WIN ALL THE COURT SUITS</span></p>
                </section>
                <section>
